config/urls.py
from django.contrib import admin
from django.urls import path, include
from vehiculo.views import indexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', indexView, name= 'index'),
    path('vehiculo/', include('vehiculo.urls')),

]

vehiculo/urls.py
from django.urls import path
from .views import *

urlpatterns = [ 
    path('', indexView, name = 'index'),
    path('add/',addVehiculo , name = 'addform'),
    path('registro/',registro_view,name="registro"),
    path('login/', login_view, name="login"),
    path('listar/', listar_vehiculo, name = 'listar'),
    path('logout/', logout_view ,name='logout'),
]

vehiculo/models.py
from django.db import models

# Create your models here.


class VehiculoModel(models.Model):
    MARCAS_OPTIONS = (
        ('Fiat','Fiat'),
        ('Chevrolet','Chevrolet'),
        ('Ford','Ford'),
        ('Toyota','Toyota'),
)
    CATEGORIAS_OPTIONS =(
        ('Particular','Particular'),
        ('Transporte','Transporte'),
        ('Carga','Carga'),
    )

    marca = models.CharField(max_length=20 , choices=MARCAS_OPTIONS,default= 'Ford')
    modelo = models.CharField(max_length=100)
    serial_carroceria = models.CharField(max_length=50)
    serial_motor = models.CharField(max_length=50)
    categoria = models.CharField(max_length=20, choices = CATEGORIAS_OPTIONS,default='Particular')
    precio = models.IntegerField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now_add=True)

    class Meta:
        permissions =(
            ("visualizar_catalogo","Puede visualizar_catalogo"),
    )


    def __str__(self):
        return self.marca

vehiculo/forms.py
from django import forms

from .models import VehiculoModel
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class VehiculoForm(forms.ModelForm):
    class Meta:
        model = VehiculoModel
        fields ="__all__"

class RegistroUsuarioForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username","email","password1","password2")

    def save(self,commit=True):
        user = super(RegistroUsuarioForm, self).save(commit=False)
        user.email =self.cleaned_data['email']
        if commit:
            user.save() 
        return user                

vehiculo/views.py
from django.shortcuts import render
from django.contrib import messages
from .forms import VehiculoForm, RegistroUsuarioForm
from tokenize import PseudoExtras
from django.contrib.auth import login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from .models import VehiculoModel


def indexView(request):
    template_name = 'index.html'
    return render(request, template_name)


def addVehiculo(request):
    form = VehiculoForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        form = VehiculoForm()
        messages.success(request, 'Los datos de han procesado exitosamente!')
    return render(request, "addform.html", {'form': form})


# registro
def registro_view(request):
    if request.method == "POST":
        form = RegistroUsuarioForm(request.POST)
        if form.is_valid():
            content_type = ContentType.objects.get_for_model(VehiculoModel)
            visualizar_catalogo = Permission.objects.get(
                codename='visualizar_catalogo', content_type=content_type)
            user = form.save()
            user.user_permissions.add(visualizar_catalogo)
            login(request, user)
            messages.success(request, "Registrado Satisfactoriamente")
            return HttpResponseRedirect('/')

        messages.error(
            request, "Registro invalido.Algunos datos no son correctos")
    form = RegistroUsuarioForm()
    context = {"register_form": form}
    return render(request, "registro.html", context)

# login


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Iniciaste sesion como : {username}.")
                return HttpResponseRedirect('/')
            else:
                messages.error(request, "Invalido username o password")
        else:
            messages.error(request, "Invalido username o password")

    form = AuthenticationForm()
    context = {"login_form": form}
    return render(request, "login.html", context)


def listar_vehiculo(request):
    vehiculos = VehiculoModel.objects.all()
    context = {'lista_vehiculos': vehiculos}
    print(vehiculos)
    print(request.user.get_all_permissions())
    return render(request, 'listar.html', context)


def logout_view(request):
    logout(request)
    messages.info(request, "Se ha cerrado la sesion satisfactoriamente. ")
    return HttpResponseRedirect('/')

templates/addform.html
{% extends 'base.html' %}
{% block content %}
<style>
    .i-am-centered {
    margin: auto;
    max-width: 300px;
    padding-top: 20%;
    border: 1px solid rgb(159, 204, 159);
    padding: 40px;
    margin-top: 40px;
    }
    </style>
<div class="i-am-centered">
    {% if perms.vehiculo.visualizar_catalogo and perms.vehiculo.add_vehiculomodel %}
    <h3 class="text-center">Ingresar Vehiculo</h3>
    <form class="p-3" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label>Marca</label>
            {{ form.marca }}
            <div class="form-group">
                <label>Modelo</label>
                {{ form.modelo }}
            </div>
            <div class="form-group">
                <label>Serial carroceria:</label>
                {{ form.serial_carroceria }}
            </div>
            <div class="form-group">
                <label>Serial Motor:</label>
                {{ form.serial_motor }}
            </div>
            <div class="form-group mt-2">
                <label>Categoria:</label>
                {{ form.categoria }}
            </div>
            <div class="form-group">
                <label>Precio:</label>
                {{ form.precio }}
            </div>
            <button type="submit" class="btn btn-success mt-3">Enviar</button>
        </div>    
    </form>
    {% else %}
      <h3>Necesitas tener permisos para agregar un vehiculo</h3>
    {% endif %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vehiculos APP</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
</head>

<body>
   

    {% block nav %}
        {% include 'menu.html' %}
    {% endblock nav %}

    {% block content %}
    {% endblock content %}

    {% block footer %}
    {% endblock footer %}

 
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
 <h1 class="mt-3 text-center">Catalogo de Vehículos</h1>
{% endblock %}

templates/listar.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container py-5" id="vehiculo-list">
    {% if user.is_authenticated %}
      <div class="title py-3">
        <h1>Listado de Vehiculos</h1>
      </div>
      <div class="card" id="card-list">
        <table class="table table-hover text-center table-responsive-sm">
          <thead>
            <tr>
              <th>Marca</th>
              <th>Modelo</th>
              <th>Serial Carroceria</th>
              <th>Serial Motor</th>
              <th>Categoria</th>
              <th>Precio</th>
              <th>Condicion de Precio</th>
            </tr>
          </thead>
          <tbody>
            {% for item in lista_vehiculos %}
              <tr>
                <td>{{ item.marca }}</td>
                <td>{{ item.modelo }}</td>
                <td>{{ item.serial_carroceria }}</td>
                <td>{{ item.serial_motor }}</td>
                <td>{{ item.categoria }}</td>
                <td>{{ item.precio }}</td>
                <td>
                  {% if item.precio > 30000 %}
                    Alto{% elif item.precio > 10000 and item.precio <= 30000 %}Medio{% elif item.precio <= 10000 %}Bajo
                  {% else %}
                    Valor invalido
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <h3>Necesitas estar registrado para ver el listado</h3>
    {% endif %}
  </div>
{% endblock %}

templates/login.html
{% include "menu.html" %} 
{% block content %} 
    {% load crispy_forms_tags %} 
    <!-- login -->
    <div class="containe py-5">
        <h1>Login</h1>
        <form method="POST">
            {% csrf_token %} 
            {{ login_form | crispy }} 
            <button class="btn btn-primary" type="submit">Login</button>
        </form>
        <p class="text-center">
            Si no tienes cuenta ,registrate en <a href="/vehiculo/registro">,para crear una cuenta</a>.
        </p>
    </div>
{% endblock %}  

templates/menu.html
{% extends 'base.html' %}
{% block nav %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Vehiculos</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'addform' %}">Agregar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'listar' %}">Listar</a>
          </li>
        </ul>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/vehiculo/logout">Salir</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Hola {{user.username}}</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/vehiculo/login">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
{% endblock %}

templates/registro.html
{% include "menu.html" %}
{% block content %} 
    {% load crispy_forms_tags %} 

    <!-- registro -->
    <div class="container py-5">
        <h1>Registro</h1>
        <form method="POST">
            {% csrf_token %}
            {{ register_form|crispy }}
            <button class="btn btn-primary" type="submit">Registrar</button>
        </form>
        <p class="text-center">
            Si tienes actualmente una cuenta, inicie su sesion en 
            <a href="/login">login</a>
        </p>
    </div>
{% endblock %}    